/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 */
import net.ltgt.gradle.errorprone.errorprone

plugins {
   application
    id("net.ltgt.errorprone") version "2.0.2"
}

repositories {
    mavenCentral()
}


buildscript {

    repositories {
        maven {
            url = uri("https://plugins.gradle.org/m2/")
        }
    }

    dependencies {
        classpath("net.ltgt.gradle:gradle-errorprone-plugin:2.0.2")
    }

}

apply(plugin = "net.ltgt.errorprone")

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.2")
    compileOnly("com.google.errorprone:error_prone_core:2.15.0")
    implementation("org.slf4j:slf4j-api:2.0.0-alpha7")

    testImplementation("com.google.guava:guava-testlib:31.1-jre")
    implementation("com.google.guava:guava:31.1-jre")

//    implementation(project(":calculator"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")
    testImplementation("com.google.guava:guava-testlib:31.1-jre")
    testImplementation("org.slf4j:slf4j-log4j12:2.0.0-alpha7")
    // Logging libs
    implementation("com.google.flogger:flogger:0.7.4")
    implementation("com.google.flogger:flogger-log4j2-backend:0.7.4")
    implementation ("org.json:json:20211205")
    implementation ("com.google.code.gson:gson:2.9.1")
    implementation(project(":services"))

}

application {
    // Define the main class for the application.
    mainClass.set("filehub.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.withType<JavaCompile>().configureEach {
    options.errorprone.disableWarningsInGeneratedCode.set(true)
}

tasks.named<JavaCompile>("compileTestJava") {
    options.errorprone.isEnabled.set(false)
}
